[package]
name = "ss-client"
version = "0.1.0"
authors = ["Italo Maia <italo.maia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
regex = "1"
lazy_static = "1.4.0"